aws:
  dynamodb:
    endpoint: http://localhost:8088

cors:
  url: http://localhost:8090

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

security:
  oauth2:
    client:
      clientId: do-not-use-in-dev
      clientSecret: do-not-use-in-dev